java -jar ./etc/synthea-with-dependencies.jar -c ./etc/synthea.properties -p 1212 "Alabama" --exporter.csv.append_mode=false 
java -jar ./etc/synthea-with-dependencies.jar -c ./etc/synthea.properties -p 178 "Alaska" 
java -jar ./etc/synthea-with-dependencies.jar -c ./etc/synthea.properties -p 1717 "Arizona" 
java -jar ./etc/synthea-with-dependencies.jar -c ./etc/synthea.properties -p 729 "Arkansas" 
java -jar ./etc/synthea-with-dependencies.jar -c ./etc/synthea.properties -p 9572 "California" 
java -jar ./etc/synthea-with-dependencies.jar -c ./etc/synthea.properties -p 1388 "Colorado" 
java -jar ./etc/synthea-with-dependencies.jar -c ./etc/synthea.properties -p 874 "Connecticut" 
java -jar ./etc/synthea-with-dependencies.jar -c ./etc/synthea.properties -p 238 "Delaware" 
java -jar ./etc/synthea-with-dependencies.jar -c ./etc/synthea.properties -p 165 "District of Columbia" 
java -jar ./etc/synthea-with-dependencies.jar -c ./etc/synthea.properties -p 5177 "Florida" 
java -jar ./etc/synthea-with-dependencies.jar -c ./etc/synthea.properties -p 2578 "Georgia" 
java -jar ./etc/synthea-with-dependencies.jar -c ./etc/synthea.properties -p 352 "Hawaii" 
java -jar ./etc/synthea-with-dependencies.jar -c ./etc/synthea.properties -p 439 "Idaho" 
java -jar ./etc/synthea-with-dependencies.jar -c ./etc/synthea.properties -p 3110 "Illinois" 
java -jar ./etc/synthea-with-dependencies.jar -c ./etc/synthea.properties -p 1638 "Indiana" 
java -jar ./etc/synthea-with-dependencies.jar -c ./etc/synthea.properties -p 771 "Iowa" 
java -jar ./etc/synthea-with-dependencies.jar -c ./etc/synthea.properties -p 711 "Kansas" 
java -jar ./etc/synthea-with-dependencies.jar -c ./etc/synthea.properties -p 1090 "Kentucky" 
java -jar ./etc/synthea-with-dependencies.jar -c ./etc/synthea.properties -p 1129 "Louisiana" 
java -jar ./etc/synthea-with-dependencies.jar -c ./etc/synthea.properties -p 329 "Maine" 
java -jar ./etc/synthea-with-dependencies.jar -c ./etc/synthea.properties -p 1491 "Maryland" 
java -jar ./etc/synthea-with-dependencies.jar -c ./etc/synthea.properties -p 1696 "Massachusetts" 
java -jar ./etc/synthea-with-dependencies.jar -c ./etc/synthea.properties -p 2441 "Michigan" 
java -jar ./etc/synthea-with-dependencies.jar -c ./etc/synthea.properties -p 1375 "Minnesota" 
java -jar ./etc/synthea-with-dependencies.jar -c ./etc/synthea.properties -p 719 "Mississippi" 
java -jar ./etc/synthea-with-dependencies.jar -c ./etc/synthea.properties -p 1490 "Missouri" 
java -jar ./etc/synthea-with-dependencies.jar -c ./etc/synthea.properties -p 261 "Montana" 
java -jar ./etc/synthea-with-dependencies.jar -c ./etc/synthea.properties -p 473 "Nebraska" 
java -jar ./etc/synthea-with-dependencies.jar -c ./etc/synthea.properties -p 742 "Nevada" 
java -jar ./etc/synthea-with-dependencies.jar -c ./etc/synthea.properties -p 332 "New Hampshire" 
java -jar ./etc/synthea-with-dependencies.jar -c ./etc/synthea.properties -p 2240 "New Jersey" 
java -jar ./etc/synthea-with-dependencies.jar -c ./etc/synthea.properties -p 511 "New Mexico" 
java -jar ./etc/synthea-with-dependencies.jar -c ./etc/synthea.properties -p 4880 "New York" 
java -jar ./etc/synthea-with-dependencies.jar -c ./etc/synthea.properties -p 2515 "North Carolina" 
java -jar ./etc/synthea-with-dependencies.jar -c ./etc/synthea.properties -p 187 "North Dakota" 
java -jar ./etc/synthea-with-dependencies.jar -c ./etc/synthea.properties -p 2855 "Ohio" 
java -jar ./etc/synthea-with-dependencies.jar -c ./etc/synthea.properties -p 957 "Oklahoma" 
java -jar ./etc/synthea-with-dependencies.jar -c ./etc/synthea.properties -p 1020 "Oregon" 
java -jar ./etc/synthea-with-dependencies.jar -c ./etc/synthea.properties -p 3147 "Pennsylvania" 
java -jar ./etc/synthea-with-dependencies.jar -c ./etc/synthea.properties -p 264 "Rhode Island" 
java -jar ./etc/synthea-with-dependencies.jar -c ./etc/synthea.properties -p 1232 "South Carolina" 
java -jar ./etc/synthea-with-dependencies.jar -c ./etc/synthea.properties -p 213 "South Dakota" 
java -jar ./etc/synthea-with-dependencies.jar -c ./etc/synthea.properties -p 1664 "Tennessee" 
java -jar ./etc/synthea-with-dependencies.jar -c ./etc/synthea.properties -p 7002 "Texas" 
java -jar ./etc/synthea-with-dependencies.jar -c ./etc/synthea.properties -p 784 "Utah" 
java -jar ./etc/synthea-with-dependencies.jar -c ./etc/synthea.properties -p 155 "Vermont" 
java -jar ./etc/synthea-with-dependencies.jar -c ./etc/synthea.properties -p 2082 "Virginia" 
java -jar ./etc/synthea-with-dependencies.jar -c ./etc/synthea.properties -p 1848 "Washington" 
java -jar ./etc/synthea-with-dependencies.jar -c ./etc/synthea.properties -p 436 "West Virginia" 
java -jar ./etc/synthea-with-dependencies.jar -c ./etc/synthea.properties -p 1424 "Wisconsin" 
java -jar ./etc/synthea-with-dependencies.jar -c ./etc/synthea.properties -p 139 "Wyoming" 
