# match.R

# This R script loads in the Synthea-generated synthetic patients that were 
# generated by the shell script that initiates 51 state-by-state Synthea runs,
# and then matches each of the Synteha-generated patients to one of the 
# Medical Expenditure Panel Survey (MEPS) respondent details based on a list
# of important-to-healthcare-analytics factors using a 1:N matching method.

# The factors used for matching are given below.

# Required libraries
library(tidyverse)
library(tidycensus)
library(MatchIt)

# This one needs specific installation - for that, uncomment the line below.
# devtools::install_github("e-mitchell/meps_r_pkg/MEPS")
library(MEPS)

# Download the 2019 - 2021 Full Year Consolidated Data Files
# https://meps.ahrq.gov/mepsweb/data_stats/download_data_files.jsp
fyc21 <- MEPS::read_MEPS(year = 2021, type = "FYC")
fyc20 <- MEPS::read_MEPS(year = 2020, type = "FYC")
fyc19 <- MEPS::read_MEPS(year = 2019, type = "FYC")

# Select relevant fields from our FYC files and pool respondent files.
# Pooling caveats/instructions are located here:
# https://meps.ahrq.gov/data_stats/download_data/pufs/h036/h36u20doc.shtml#2

fyc21_demos <- fyc21 %>% 
  select(DUPERSID, DUID, PID, FAMID21, MARRY21X, SPOUID21, DOBMM, DOBYY, 
         AGELAST, REGION21, SEX, RACETHX, OTHLGSPK, WHTLGSPK, HWELLSPK, BORNUSA, 
         YRSINUS, HIDEG, POVLEV21, POVCAT21, INSURC21, PERWT21F, TTLP21X, 
         RXEXP21, TOTEXP21, TOTSLF21, ERTOT21, IPNGTD21, IPDIS21, HHTOTD21, 
         RXTOT21, VARSTR, VARPSU) %>% 
  rename(FAMIDYY=FAMID21,
         MARRYYYX=MARRY21X,
         SPOUIDYY=SPOUID21,
         REGIONYY=REGION21,
         POVLEVYY=POVLEV21,
         POVCATYY=POVCAT21,
         INSURCYY=INSURC21,
         PERWTYYF=PERWT21F,
         TTLPYYX=TTLP21X,
         RXEXPYY=RXEXP21,
         TOTEXPYY=TOTEXP21,
         TOTSLFYY=TOTSLF21,
         ERTOTYY=ERTOT21,
         IPNGTDYY=IPNGTD21,
         IPDISYY=IPDIS21,
         HHTOTDYY=HHTOTD21,
         RXTOTYY=RXTOT21) %>% 
  mutate(MEPS_DATA_YEAR = 2021) %>% 
  mutate(DUPERSID = paste0(DUPERSID, MEPS_DATA_YEAR))

fyc20_demos <- fyc20 %>% 
  select(DUPERSID, DUID, PID, FAMID20, MARRY20X, SPOUID20, DOBMM, DOBYY, 
         AGELAST, REGION20, SEX, RACETHX, OTHLGSPK, WHTLGSPK, HWELLSPK, BORNUSA, 
         YRSINUS, HIDEG, POVLEV20, POVCAT20, INSURC20, PERWT20F, TTLP20X,
         RXEXP20, TOTEXP20, TOTSLF20, ERTOT20, IPNGTD20, IPDIS20, HHTOTD20, 
         RXTOT20, VARSTR, VARPSU) %>% 
  rename(FAMIDYY=FAMID20,
         MARRYYYX=MARRY20X,
         SPOUIDYY=SPOUID20,
         REGIONYY=REGION20,
         POVLEVYY=POVLEV20,
         POVCATYY=POVCAT20,
         INSURCYY=INSURC20,
         PERWTYYF=PERWT20F,
         TTLPYYX=TTLP20X,
         RXEXPYY=RXEXP20,
         TOTEXPYY=TOTEXP20,
         TOTSLFYY=TOTSLF20,
         ERTOTYY=ERTOT20,
         IPNGTDYY=IPNGTD20,
         IPDISYY=IPDIS20,
         HHTOTDYY=HHTOTD20,
         RXTOTYY=RXTOT20) %>% 
  mutate(MEPS_DATA_YEAR = 2020) %>% 
  mutate(DUPERSID = paste0(DUPERSID, MEPS_DATA_YEAR))

fyc19_demos <- fyc19 %>% 
  select(DUPERSID, DUID, PID, FAMID19, MARRY19X, SPOUID19, DOBMM, DOBYY, 
         AGELAST, REGION19, SEX, RACETHX, OTHLGSPK, WHTLGSPK, HWELLSPK, BORNUSA, 
         YRSINUS, HIDEG, POVLEV19, POVCAT19, INSURC19, PERWT19F, TTLP19X,
         RXEXP19, TOTEXP19, TOTSLF19, ERTOT19, IPNGTD19, IPDIS19, HHTOTD19, 
         RXTOT19, VARSTR, VARPSU) %>% 
  rename(FAMIDYY=FAMID19,
         MARRYYYX=MARRY19X,
         SPOUIDYY=SPOUID19,
         REGIONYY=REGION19,
         POVLEVYY=POVLEV19,
         POVCATYY=POVCAT19,
         INSURCYY=INSURC19,
         PERWTYYF=PERWT19F,
         TTLPYYX=TTLP19X,
         RXEXPYY=RXEXP19,
         TOTEXPYY=TOTEXP19,
         TOTSLFYY=TOTSLF19,
         ERTOTYY=ERTOT19,
         IPNGTDYY=IPNGTD19,
         IPDISYY=IPDIS19,
         HHTOTDYY=HHTOTD19,
         RXTOTYY=RXTOT19) %>% 
  mutate(MEPS_DATA_YEAR = 2019) %>% 
  mutate(DUPERSID = paste0(DUPERSID, MEPS_DATA_YEAR))

full_3yr_fyc <- fyc21_demos %>% 
  union_all(fyc20_demos) %>% 
  union_all(fyc19_demos) %>% 
  filter(AGELAST >= 18) %>% 
  filter(PERWTYYF > 0) %>% 
  filter(DOBYY > 0, DOBMM > 0)

# Determine basic characteristics of respondents that we can use or manipulate
# in order to match them to our Synthea-generated patients on comparable
# demographic attributes.

# Read in Synthetic dataset you have generated.
synthea_out_path <- "./etc/output/csv/"

# Read in full results of patients
synthea_people <- read_csv(paste0(synthea_out_path, "patients.csv"))

# Build a crosswalk of State Name to US Census Region
state_region_map <- tibble(state=state.name, region=state.region) %>% 
  union_all(tibble(state="District of Columbia", region="South"))

# Begin to massage Synthea field values to prepare for matching against
# MEPS FYC dataset field details.
synthea_people_matchdata <- synthea_people %>% 
  select(Id, BIRTHDATE, RACE, ETHNICITY, GENDER, MARITAL, STATE, INCOME) %>% 
  left_join(state_region_map, by=c("STATE"="state")) %>% 
  rename("REGIONYY"="region") %>% 
  select(-STATE) %>% 
  mutate(INCOME_PCT = percent_rank(INCOME)) %>% 
  select(-INCOME) %>% 
  mutate(AGELAST = (ymd(20211231) - ymd(BIRTHDATE)) / dyears(1)) %>% 
  mutate(AGELAST = if_else(AGELAST>85, 85, AGELAST)) %>% 
  mutate(DOBYY = if_else(AGELAST == 85, 1936, year(ymd(BIRTHDATE))),
         DOBMM = month(ymd(BIRTHDATE))) %>% 
  mutate(RACETHX = case_when(
    ETHNICITY == "hispanic" ~ "HISPANIC",
    RACE == "white" ~ "NON-HISPANIC WHITE ONLY",
    RACE == "black" ~ "NON-HISPANIC BLACK ONLY",
    RACE == "asian" ~ "NON-HISPANIC ASIAN ONLY",
    .default = "NON-HISPANIC OTHER RACE OR MULTIPLE RACE")) %>% 
  select(-RACE, -ETHNICITY) %>% 
  mutate(MARITAL = if_else(is.na(MARITAL), "S", MARITAL)) %>% 
  filter(AGELAST >= 18)

# Read in Payer Transitions to discover current Health Plan at EOY 2021
payer_transitions <- read_csv(paste0(synthea_out_path, "payer_transitions.csv"))
payers <- read_csv(paste0(synthea_out_path, "payers.csv")) %>% 
  distinct(Id, NAME, OWNERSHIP)

# Only capture payer transitions where 12/31/2022 is in between start date and 
# end date. We will assume payer status as of 12/31/2021 is the full-year payer 
# status of the MEPS respondent that is matched. Might make this more
# sophisticated later, but for now keeping it simple.

payer_transitions_filter <- payer_transitions %>% 
  mutate(start_dt = as_date(START_DATE),
         end_dt = as_date(END_DATE)) %>% 
  filter(start_dt <= ymd(20211231),
         end_dt >= ymd(20211231)) %>% 
  inner_join(payers, by=c("PAYER"="Id")) %>% 
  left_join(payers, by=c("SECONDARY_PAYER"="Id")) %>% 
  select(PATIENT, NAME.x, OWNERSHIP.x, NAME.y, OWNERSHIP.y) %>% 
  rename(PRIMARY_PAYER = NAME.x,
         PRIMARY_PAYER_ORG = OWNERSHIP.x,
         SECONDARY_PAYER = NAME.y,
         SECONDARY_PAYER_ORG = OWNERSHIP.y)

synthea_people_matchdata_payerdeets <- synthea_people_matchdata %>% 
  inner_join(payer_transitions_filter, by=c("Id"="PATIENT")) %>% 
  mutate(Medicare_Aged = if_else(AGELAST <= 65, 
                                 "<65", "65+")) %>%  # USE <65 for MCare elig 
  mutate(INSURCYY = case_when(
    Medicare_Aged == "<65" & 
      PRIMARY_PAYER_ORG == "PRIVATE" ~ "<65 ANY PRIVATE",
    Medicare_Aged == "<65" & 
      PRIMARY_PAYER_ORG == "GOVERNMENT" ~ "<65 PUBLIC ONLY",
    Medicare_Aged == "<65" & 
      PRIMARY_PAYER_ORG == "NO_INSURANCE" ~ "<65 UNINSURED",
    Medicare_Aged == "65+" & 
      (PRIMARY_PAYER == "Medicare" &  # Traditional MCare 65+
         is.na(SECONDARY_PAYER_ORG)) ~ "65+ EDITED MEDICARE ONLY",
    Medicare_Aged == "65+" & 
      (PRIMARY_PAYER_ORG == "GOVERNMENT" &  #Duals + Medicaid that are 65+
         is.na(SECONDARY_PAYER_ORG)) ~ "65+ EDITED MEDICARE AND OTH PUB ONLY",
    Medicare_Aged == "65+" & 
      (PRIMARY_PAYER == "Medicare" &  # Medicare Adv OR Medigap - we'll use income pct to split
         SECONDARY_PAYER_ORG == "PRIVATE" & 
         (INCOME_PCT > .7 | INCOME_PCT < .2)) ~ "65+ EDITED MEDICARE AND PRIVATE", 
    Medicare_Aged == "65+" &
      (PRIMARY_PAYER == "Medicare" &
         SECONDARY_PAYER_ORG == "PRIVATE" &
         INCOME_PCT <= .7 & INCOME_PCT >= .2) ~ "65+ EDITED MEDICARE ONLY",
    Medicare_Aged == "65+" ~ "65+ UNINSURED")) %>% 
  select(-PRIMARY_PAYER, -PRIMARY_PAYER_ORG, -SECONDARY_PAYER, 
         -SECONDARY_PAYER_ORG, -Medicare_Aged) %>% 
  mutate(SEX = str_to_upper(GENDER)) %>% 
  select(-GENDER) %>% 
  mutate(AGE_GRP_9 = case_when(AGELAST < 5 ~ "Under 5",
                               AGELAST >= 5 & AGELAST < 18 ~ "5 - 17",
                               AGELAST >= 18 & AGELAST < 30 ~ "18 - 29",
                               AGELAST >= 30 & AGELAST < 40 ~ "30 - 39",
                               AGELAST >= 40 & AGELAST < 50 ~ "40 - 49",
                               AGELAST >= 50 & AGELAST < 60 ~ "50 - 59",
                               AGELAST >= 60 & AGELAST < 70 ~ "60 - 69",
                               AGELAST >= 70 & AGELAST < 80 ~ "70 - 79",
                               AGELAST >= 80 ~ "80 and over",
                               T ~ as.character(AGELAST))) %>%
  relocate(AGE_GRP_9, .after=AGELAST) %>% 
  mutate(MEPS_respondent = 0)

# Now let's do the same for our MEPS dataset, getting it to be totally 
# conformant with the dataset we just created above.


meps_matchdata <- full_3yr_fyc %>% 
  select(DUPERSID, MARRYYYX, REGIONYY, TTLPYYX, AGELAST, DOBYY, DOBMM, RACETHX, 
         INSURCYY, SEX, MEPS_DATA_YEAR) %>% 
  filter(REGIONYY > 0) %>% 
  rename(Id = DUPERSID) %>% 
  mutate(MARITAL = case_when(
    MARRYYYX == 1 ~ "M",
    MARRYYYX == 5 ~ "S",
    MARRYYYX == 2 ~ "W",
    MARRYYYX == 3 | MARRYYYX == 4 ~ "D",
    .default = "S")) %>% 
  select(-MARRYYYX) %>% 
  relocate(MARITAL, .after=Id) %>% 
  mutate(INCOME_PCT = percent_rank(TTLPYYX)) %>% 
  select(-TTLPYYX) %>% 
  mutate(REGION = case_when(
    REGIONYY == 1 ~ "Northeast",
    REGIONYY == 2 ~ "North Central",
    REGIONYY == 3 ~ "South",
    REGIONYY == 4 ~ "West")) %>% 
  select(-REGIONYY) %>% 
  rename(REGIONYY = REGION) %>% 
  mutate(DOBYY = as.numeric(DOBYY),
         DOBMM = as.numeric(DOBMM),
         BIRTHDATE = mdy(paste(month(DOBMM, label=T), floor(28*runif(1)), DOBYY))) %>% 
  mutate(AGELAST = (ymd(paste0(MEPS_DATA_YEAR, "1231")) - ymd(BIRTHDATE)) / dyears(1)) %>% 
  mutate(AGE_GRP_9 = case_when(AGELAST < 5 ~ "Under 5",
                               AGELAST >= 5 & AGELAST < 18 ~ "5 - 17",
                               AGELAST >= 18 & AGELAST < 30 ~ "18 - 29",
                               AGELAST >= 30 & AGELAST < 40 ~ "30 - 39",
                               AGELAST >= 40 & AGELAST < 50 ~ "40 - 49",
                               AGELAST >= 50 & AGELAST < 60 ~ "50 - 59",
                               AGELAST >= 60 & AGELAST < 70 ~ "60 - 69",
                               AGELAST >= 70 & AGELAST < 80 ~ "70 - 79",
                               AGELAST >= 80 ~ "80 and over",
                               T ~ as.character(AGELAST))) %>%
  mutate(RACE_ETH = case_when(
    RACETHX == 1 ~ "HISPANIC",
    RACETHX == 2 ~ "NON-HISPANIC WHITE ONLY",
    RACETHX == 3 ~ "NON-HISPANIC BLACK ONLY",
    RACETHX == 4 ~ "NON-HISPANIC ASIAN ONLY",
    .default = "NON-HISPANIC OTHER RACE OR MULTIPLE RACE")) %>% 
  select(-RACETHX) %>% 
  rename(RACETHX = RACE_ETH) %>% 
  mutate(GENDER = case_when(
    SEX == 1 ~ "M",
    SEX == 2 ~ "F",
    .default = "M")) %>% 
  select(-SEX) %>% 
  rename(SEX = GENDER) %>% 
  mutate(ins = case_when(
    INSURCYY == 1 ~ "<65 ANY PRIVATE",
    INSURCYY == 2 ~ "<65 PUBLIC ONLY",
    INSURCYY == 3 ~ "<65 UNINSURED",
    INSURCYY == 4 ~ "65+ EDITED MEDICARE ONLY",
    INSURCYY == 5 ~ "65+ EDITED MEDICARE AND PRIVATE",
    INSURCYY == 6 ~ "65+ EDITED MEDICARE AND OTH PUB ONLY",
    INSURCYY == 7 ~ "65+ UNINSURED",
    INSURCYY == 8 ~ "65+ NO MEDICARE AND ANY PUBLIC/PRIVATE",
    .default = "UNINSURED")) %>% 
  select(-INSURCYY) %>% 
  rename(INSURCYY = ins) %>% 
  relocate(REGIONYY, .after=MARITAL) %>% 
  relocate(INCOME_PCT, .after=REGIONYY) %>% 
  relocate(AGELAST, .after=INCOME_PCT) %>% 
  relocate(AGE_GRP_9, .after=AGELAST) %>% 
  relocate(DOBYY, .after=AGE_GRP_9) %>% 
  relocate(DOBMM, .after=DOBYY) %>% 
  relocate(RACETHX, .after=DOBMM) %>% 
  relocate(INSURCYY, .after=RACETHX) %>% 
  relocate(SEX, .after=INSURCYY) %>% 
  relocate(BIRTHDATE, .after=Id) %>% 
  mutate(MEPS_respondent = 1) %>% 
  select(-MEPS_DATA_YEAR)

# Maybe spot check frequency distributions of some of these variables to ensure consistency
table(synthea_people_matchdata_payerdeets$SEX) / count(synthea_people_matchdata_payerdeets)$n
table(meps_matchdata$SEX) / count(meps_matchdata)$n

table(synthea_people_matchdata_payerdeets$RACETHX) / count(synthea_people_matchdata_payerdeets)$n
table(meps_matchdata$RACETHX) / count(meps_matchdata)$n

table(synthea_people_matchdata_payerdeets$MARITAL) / count(synthea_people_matchdata_payerdeets)$n
table(meps_matchdata$MARITAL) / count(meps_matchdata)$n

table(synthea_people_matchdata_payerdeets$INSURCYY) / count(synthea_people_matchdata_payerdeets)$n
table(meps_matchdata$INSURCYY) / count(meps_matchdata)$n

# There is some topsy turvy in the 80+ group because MEPS truncates this while Synthea does not
table(synthea_people_matchdata_payerdeets$AGE_GRP_9) / count(synthea_people_matchdata_payerdeets)$n
table(meps_matchdata$AGE_GRP_9) / count(meps_matchdata)$n

# Union both together
union_all_patients <- synthea_people_matchdata_payerdeets %>% 
  union_all(meps_matchdata)

# Now psmatch
# We're going to want to match our MEPS population against the Synthea-simulated population on the following:
#  - AGELAST
#  - Gender (binary, sorry, it's not able to be done otherwise with MEPS)
#  - Race (white, Black, Asian, or multi/other)
#. - Ethnicity (hispanic, non-hispanic)
#. - US Census Region
#  - Income Percentile in population
#. - Marital status (Single or Married only)

# 1:1 NN PS matching w/ replacement
matched_data <-
  matchit(MEPS_respondent ~ MARITAL + SEX + RACETHX + REGIONYY + INSURCYY + AGE_GRP_9,
          data=union_all_patients,
          method = "nearest",
          distance = "glm",
          exact = ~ MARITAL + SEX + RACETHX + REGIONYY + INSURCYY + AGE_GRP_9,
          replace=F,
          ratio=3)

# Evaluate post-match distribution - this can take a while!
match_summary <- summary(matched_data)
match_summary

plot(matched_data, type = "density", interactive = FALSE,
     which.xs = ~MARITAL + SEX + RACETHX + REGIONYY + INSURCYY + AGE_GRP_9)

# Obtain matched dataset
matched_datset <- match.data(matched_data)

matched_meps <- matched_datset %>% 
  filter(MEPS_respondent == 1) %>% 
  arrange(subclass)

matched_synthea <- matched_datset %>% 
  filter(MEPS_respondent == 0) %>% 
  arrange(subclass)

# Join back to Synthea details for name and demo data that I've simulated to fill in the gaps - MEPS respondents can be
# re-used but they will assume the personal details generated by Synthea outside of the matching paremeters.

final_matchup <- matched_synthea %>% 
  left_join(matched_meps, by=c("subclass")) %>% 
  select(Id.x, Id.y, RACETHX.x, AGE_GRP_9.x, SEX.x, AGELAST.x, subclass) %>% 
  rename(MEPS_ID = Id.y, 
         Synthea_ID = Id.x,
         AGE_GRP_9 = AGE_GRP_9.x,
         AGELAST = AGELAST.x,
         SEX = SEX.x,
         RACETHX = RACETHX.x)
